import pandas as pd
import umap  # For dimensionality reduction
from .pipeline_orchestrator import PipelineOrchestrator # To use the normalization pipeline from pipeline_orchestrator.py






#function to perform dimensionality reduction using UMAP and visualize the clusters using a normalized dataset generated by the vectorizer.py pipeline
def cluster_and_visualize(df,config, n_neighbors=15, min_dist=0.1, n_components=2, metric='cosine'): #TODO: we can add more parameters to the function to make it more flexible, like the number of clusters, the type of visualization, etc. and we can move the config parameter to the config.yaml file as well.
    """
    Performs UMAP dimensionality reduction and prepares the DataFrame for visualization.
    Returns:
        pd.DataFrame: The original dataframe with added 'x', 'y', and 'cluster' columns.
    """
    # Step 1: Normalize the data using the pipeline from pipeline_orchestrator.py
    # We filter the dataframe to include only questions (PostTypeId == 1) since
    # we are interested in clustering questions based on their features. This ensures that we are working with a consistent set of data for the clustering process.
    df_filtered = df[df['PostTypeId'] == 1].copy()
    # Step 2: Normalize the data using the pipeline from pipeline_orchestrator.py
   # Initialize the orchestrator
    orchestrator = PipelineOrchestrator(config=config)
    # Retrieve the pipeline object
    preprocessing_pipeline = orchestrator.get_pipeline()
    #We fit_transform the pipeline on the filtered dataframe to get the normalized data ready for UMAP. 
    # The fit_transform method applies all the transformations defined in the pipeline to the input DataFrame and returns a transformed version of the data that is suitable for clustering and visualization.
    normalized_data = preprocessing_pipeline.fit_transform(df_filtered)

    # Step 3: Perform UMAP dimensionality reduction
    reducer = umap.UMAP(
        n_neighbors=n_neighbors, 
        min_dist=min_dist, 
        n_components=n_components, 
        metric=metric,
        random_state=42 # We set a random state for reproducibility of the UMAP results. we picked 42 because it's cool!
        )
    embedding = reducer.fit_transform(normalized_data)
    
    # Step 4: add coordinate to dataframe for visualization
    df_filtered['x'] = embedding[:, 0]
    df_filtered['y'] = embedding[:, 1]

    #Step 5: Create 'cluster' column for coloring.
    # Visualizer uses this column to assign colors to points based on their cluster labels.
    # create readable cluster label based on AnswerCount column in the original data frame, "Answered" if the value is > 0, "Unanswered" otherwise
    df_filtered['cluster'] = df_filtered['AnswerCount'].apply(lambda x: 'Answered' if x > 0 else 'Unanswered')

    return df_filtered