import streamlit as st # For building the interactive labeling tool
import pandas as pd
import plotly.express as px # For interactive visualizations in Streamlit
import json # For handling label storage as JSON in the DataFrame
import yaml
import os # For handling file paths
import sys  

# 1. DEFINE the variable FIRST to get the project root directory, so we can reliably access files defined in config.yaml regardless of where this script is run from.
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.abspath(os.path.join(current_dir, ".."))
if project_root not in sys.path:
    sys.path.insert(0, project_root) # Now we can import modules from the src directory without worrying about relative imports or path issues.

# now we can import the cluster_and_visualize function from your existing codebase without worrying about relative imports or path issues.
from src.clustering_data import cluster_and_visualize 
# 2. Load the config.yaml file to get paths and other settings, using the project root to construct absolute paths.
config_path = os.path.join(project_root, "config.yaml")

with open(config_path, "r") as f:
    config = yaml.safe_load(f)
# 3. Define paths for the interim CSV and output directory based on the config.yaml settings.
interim_rel_path = config['paths']['interim_csv']
INTERIM_PATH = os.path.join(project_root, interim_rel_path) # Absolute path to the interim CSV
output_rel_path = config['paths']['output_dir']
OUTPUT_DIR = os.path.join(project_root, output_rel_path) # Absolute path to the output directory

# --- DATA PROCESSING ---
@st.cache_data # Cache the function to avoid re-running clustering on every interaction, only re-run if the underlying data changes
def get_clustered_data():
    """
    Reads the CSV defined in config.yaml and runs the 
    existing clustering logic to get x, y, and cluster columns.
    """
    if not os.path.exists(INTERIM_PATH): # Check if the interim CSV exists before trying to read it
        st.error(f"Could not find data at {INTERIM_PATH}. Please run Data Ingestion first.")
        return None
    
    df = pd.read_csv(INTERIM_PATH) # Read the data from the interim CSV path defined in config.yaml and load it into a DataFrame
    # Run the existing clustering and visualization logic from clustering_data.py to get the clustered DataFrame with x, y, and cluster columns
    cluster_df = cluster_and_visualize(df, config, metric='euclidean')
    return cluster_df # Return the clustered DataFrame for use in the Streamlit app

# Initialize session state so we don't lose labels on every click
if 'df' not in st.session_state:
    clustered_df = get_clustered_data()
    if clustered_df is not None:
        if 'label_store' not in clustered_df.columns:
            clustered_df['label_store'] = '{}' # Initialize an empty JSON string for label storage if it doesn't exist
        st.session_state.df = clustered_df # Store the clustered DataFrame in session state for use across interactions

# --- UI LAYOUT ---
st.title("🎯 Project Labeling Interface")

if 'df' in st.session_state: # Only render the UI if we have the clustered DataFrame in session state
    col1, col2 = st.columns([3, 1]) # Use a wider column for the map and a narrower one for the annotation details

    with col1: # Map View
        st.subheader("Map View") # The map will display the clustered data points, colored by their cluster labels. Users can select points to annotate in the sidebar.
        # Create an interactive scatter plot using Plotly Express, with points colored by the 'cluster' column and hover data showing the 'Title' and 'Body' of each question.
        fig = px.scatter(
            st.session_state.df, 
            x='x', y='y', # Use the 'x' and 'y' columns generated by the clustering logic for the coordinates of the points on the map.
            color='cluster', # Color points based on the 'cluster' column which indicates whether questions are "Answered" or "Unanswered"
            hover_data=['Title', 'Body'], # Show the title and body of each question when hovering over points on the map for better context during annotation.
            height=700, # Set a fixed height for the plot to ensure it fits well within the Streamlit layout.
            template="plotly_white", # Use a clean white template for better aesthetics and readability of the plot.
            color_discrete_sequence=px.colors.qualitative.D3 # Use a qualitative color sequence from Plotly for better distinction between clusters, especially since we have categorical cluster labels.
        )
        # Enable selection of points on the plot. When a user clicks on a point, it will trigger the annotation logic in the sidebar to display details about the selected data point and allow the user to add labels.
        selected = st.plotly_chart(fig, on_select="rerun", selection_mode="points")

    with col2: # Annotation Sidebar
        st.subheader("Annotation") # The sidebar will display details about the selected data point from the map and provide input fields for the user to add labels.
        indices = selected.get("selection", {}).get("point_indices", []) # Get the indices of the selected points from the plot. This will allow us to identify which data point the user has selected for annotation and display its details in the sidebar.
        
        if indices: # If there are selected points, we will display the details of the first selected point .
            idx = indices[0] # Get the index of the first selected point to display its details in the sidebar. 
            row = st.session_state.df.iloc[idx] # Retrieve the corresponding row from the DataFrame based on the selected index to access the details of the selected data point for display and annotation in the sidebar.
            
            st.markdown(f"**Row ID:** `{idx}`") # Display the index of the selected row in the sidebar for reference, which can be useful for tracking which data point is being annotated and for debugging purposes.
            st.markdown(f"**Title:** {row.get('Title', 'N/A')}") # Display the title of the selected data point in the sidebar to provide context for the user during annotation. If the 'Title' column is missing, it will show 'N/A'.
            
            # Display the body of the selected data point in an expandable section in the sidebar to allow users to read the full content without cluttering the interface. If the 'Body' column is missing, it will show 'N/A'.
            st.divider() # Add a visual divider for better separation of sections in the sidebar.
            
            # Populate keys from config if you have them, otherwise use text_input
            manual_config = config.get('manual_label', {}) # Get the manual labeling configuration from config.yaml, which may contain predefined keys for labeling. This allows us to provide a dropdown of existing label keys for consistency, while still allowing users to input custom keys if needed.
            existing_keys = manual_config.get('keys', []) if isinstance(manual_config, dict) else [] # Extract the list of existing label keys from the configuration 
            # If there are existing keys defined in the config, we will show a selectbox for the user to choose from. 
            label_key = st.selectbox("Label Type", options=existing_keys) if existing_keys else st.text_input("Label Key")
            label_val = st.text_input("Value") # Input field for the user to enter the value for the label they want to apply to the selected data point. 
            
            if st.button("Apply Label", type="primary"): # When the user clicks the "Apply Label" button, we will update the 'label_store' JSON for the selected data point in the DataFrame with the new label key and value. 
                #This allows us to keep track of all labels applied to each data point in a structured way using JSON.
                current_labels = json.loads(row['label_store']) # Load the existing labels from the 'label_store' column, which is stored as a JSON string, into a Python dictionary so we can update it with the new label key and value.
                current_labels[label_key] = label_val # Update the dictionary with the new label key and value provided by the user in the input fields.
                st.session_state.df.at[idx, 'label_store'] = json.dumps(current_labels) # Convert the updated labels dictionary back to a JSON string and store it in the 'label_store' column of the DataFrame for the selected data point.
                st.success(f"Updated point {idx}") # Show a success message to the user indicating that the label has been applied to the selected data point. 
                st.rerun() # Rerun the Streamlit app to reflect the updated labels.
                
            st.write("**Data Point JSON:**") # Display the current labels for the selected data point in JSON format .
            st.json(json.loads(row['label_store'])) # Show the current labels for the selected data point in a JSON format.
        else:
            st.info("Select a point on the chart to annotate.") # If no points are selected, show an informational message prompting the user to select a point on the chart to start annotating.

    # --- SAVE/EXPORT ---
    st.sidebar.title("Actions") # The sidebar will also contain an "Export" button that allows the user to save the labeled data to a CSV file in the output directory defined in config.yaml.
    if st.sidebar.button("Export to Output Directory"):
        # Unpack JSON to CSV columns
        export_df = st.session_state.df.copy() # Create a copy of the DataFrame from session state to work with for exporting, so we don't modify the original DataFrame used for display and annotation in the app.
        labels_expanded = export_df['label_store'].apply(json.loads).apply(pd.Series) # Expand the 'label_store' JSON column into separate columns for each label key, so that we can have a flat CSV structure where each label key becomes its own column in the output CSV file.
        final_df = pd.concat([export_df, labels_expanded], axis=1) # Concatenate the original DataFrame with the expanded label columns to create a final DataFrame that includes all the original data along with the new columns for each label key, which will be saved to the output CSV file.
        
        # Save to path from config.yaml
        save_path = os.path.join(OUTPUT_DIR, "labeled_data_output.csv")
        final_df.to_csv(save_path, index=False)
        st.sidebar.success(f"Saved to {save_path}")